# Generated by Django 6.0.4 on 2026-05-03 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('produto_info', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=50)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=12)),
                ('responsavel', models.CharField(max_length=100)),
                ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_atual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('local', models.CharField(max_length=50)),
                ('devolvido', models.CharField(default='NÃO', max_length=10)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('DIVERSOS', 'DIVERSOS'), ('FERRAMENTAS', 'FERRAMENTAS'), ('DEFENSIVOS', 'DEFENSIVOS'), ('ADUBO', 'ADUBO')], default='DIVERSOS', max_length=50)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('local', models.CharField(choices=[('ALMOX 1', 'ALMOX 1'), ('ALMOX 2', 'ALMOX 2'), ('ALMOX 3', 'ALMOX 3'), ('ALMOX 4', 'ALMOX 4'), ('ALMOX 5', 'ALMOX 5')], default='ALMOX 1', max_length=50)),
                ('minimo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('em_uso', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
    ]
