# Generated by Django 6.0.4 on 2026-05-03 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('descricao', models.CharField(max_length=200)),
                ('km_atual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField()),
                ('custo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('km_da_manutencao', models.DecimalField(decimal_places=2, max_digits=12)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almox.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('combustivel', models.CharField(max_length=50)),
                ('litros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('km_no_abastecimento', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almox.veiculo')),
            ],
        ),
    ]
