# Generated by Django 6.0.4 on 2026-05-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almox', '0002_veiculo_manutencao_abastecimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veiculo', models.CharField(max_length=100)),
                ('ultima_manutencao', models.DateField()),
                ('proxima_manutencao', models.DateField()),
                ('tipo', models.CharField(max_length=200)),
                ('responsavel', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['proxima_manutencao'],
            },
        ),
        migrations.RemoveField(
            model_name='manutencao',
            name='veiculo',
        ),
        migrations.DeleteModel(
            name='Abastecimento',
        ),
        migrations.DeleteModel(
            name='Manutencao',
        ),
        migrations.DeleteModel(
            name='Veiculo',
        ),
    ]
