# Generated by Django 6.0.4 on 2026-05-03 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almox', '0003_controleveiculo_remove_manutencao_veiculo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controleveiculo',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
    ]
