# Generated by Django 6.0.4 on 2026-05-03 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almox', '0004_controleveiculo_concluido'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='almox.produto'),
        ),
    ]
